services:
  caddy:
    image: caddy:2.11.4
    deploy:
      mode: global

  di-agent:
    build: ./go
    restart: unless-stopped
    deploy:
      mode: global
    x-ports:
      - "9090:9090@host" 